name: build-test-lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Formatting
      run: cargo fmt --verbose -- --check
    - name: Linting
      run: cargo clippy --verbose -- -D warnings
